from diplom_alza_sk.locators.basket_locators import BasketLocators
from diplom_alza_sk.locators.context_menu_locators import ContextMenuLocators
from diplom_alza_sk.locators.header_locators import HeaderLocators
from diplom_alza_sk.locators.login_locators import LoginLocators
from diplom_alza_sk.locators.order_locators import OrderLocators